update

diff --git a/.bin/bfm b/.bin/bfm
--- a/.bin/bfm
+++ b/.bin/bfm
@@ -1,187 +1,148 @@
 #!/usr/bin/env bash
-#
-# fff - fucking fast file-manager.
 
-setup_terminal() { printf '\e[?1049h\e[?6h\e[?7l\e[?25l\e[2J\e[1;%sr' "$max_items"; }
+short() {
+   previous_dir="$PWD"
+   case "${1: -1}" in
+      /) open "/" ;;
+      a) open "$HOME/.apps" ;;
+      h) open "$HOME/Hentet" ;;
+      b) open "$HOME/.bin" ;;
+      S) open "$HOME/.Scripts" ;;
+      p) open "$HOME/Projekter" ;;
+      d) open "$HOME/.dotfiles" ;;
+      D) open "$HOME/Dokumenter" ;;
+      c) open "$HOME/.config" ;;
+      l) open "$HOME/.local" ;;
+      w) open "$HOME/Billeder/wallpapers" ;;
+      t) open "$HOME/.cache/fff/trash" ;;
+      y) open "$HOME/Movies/youtube" ;;
 
-reset_terminal() { printf '\e[?6l\e[?7h\e[?25h\e[2J\e[;r'; }
-
-clear_screen() {
-   printf '\e[%sH\e[9999C\e[1J%b\e[1;%sr' \
-      "$((LINES-2))" "${TMUX:+\e[2J}" "$max_items"
-   }
-
-get_term_size() {
-   read -r LINES COLUMNS < <(stty size)
-   ((max_items=LINES-3))
+      g) ((scroll != 0)) && ((scroll=0)) ;;
+   esac
+   redraw
 }
 
-status_line() {
-   local mark_ui="[${#marked_files[@]}] selected (${file_program[*]}) [p] ->"
+key() {
+   case "$1" in
+      l|"") open "${list[scroll]}" ;;
 
-   PWD_escaped="${PWD//[^[:print:]]/^[}"
+      h) ((search == 1 && search_end_early != 1)) && open "$PWD"
+	 [[ $PWD && $PWD != / ]] && { find_previous=1; open "${PWD%/*}"; } ;;
+      j) ((scroll < list_total)) && {
+	    ((scroll++)); ((y < max_items )) && ((y++))
+	    print_line "$((scroll-1))"
+	    printf '\n'
+	    print_line "$scroll"
+	    status_line; } ;;
+      k) ((scroll > 0)) && {
+	    ((scroll--))
+	    print_line "$((scroll+1))"
+	    ((y < 2)) && printf '\e[1L' || printf '\e[A' || ((y--))
+	    print_line "$scroll"
+	    status_line; } ;;
+      g) read -rsn 1; short "$REPLY" ;;
+      G) ((scroll != list_total)) && ((scroll=list_total)) && redraw ;;
+      O) xdg-open "${list[scroll]}" 2>/dev/null & disown ;;
+      R) [[ -x "${list[scroll]}" ]] && {
+	    reset_terminal
+      	    "${list[scroll]}"
+      	    read &>/dev/null
+      	    redraw full; } ;;
+      .) shopt_flags=(u s)
+	 shopt -"${shopt_flags[((a=a>0?0:++a))]}" dotglob
+      	 redraw full ;;
+      /) cmd_line "/" "search"
+	 if [[ -z ${list[*]} || -z $cmd_reply ]]; then
+	    list=("${cur_list[@]}")
+      	    ((list_total=${#list[@]}-1))
+      	    redraw
+      	    search=
+      	 else
+	    search=1
+      	 fi ;;
+      S) reset_terminal; cd "$PWD" && "$SHELL"
+	 setup_terminal; redraw ;;
 
-   printf '\e7\e[?6l\e[%sH\e[30;4%sm%*s\r%s %s%s\e[m\n\e[K\e[?6h\e8' \
-      "$((LINES-1))" \
-      "${FFF_COL2:-1}" \
-      "$COLUMNS" "" \
-      "($((scroll+1))/$((list_total+1)))" \
-      "${marked_files[*]:+${mark_ui}}" \
-      "${PWD_escaped:-/}"
-   }
+      y|m|d|v) mark "$scroll" "$1" ;;
 
-read_dir() {
-   local dirs=()
-   local files=()
-   local item_index
-   
-   # If '$PWD' is '/', unset it to avoid '//'.
-   [[ $PWD == / ]] && PWD=
-   
-   for item in "$PWD"/*; do
-      if [[ -d $item ]]; then
-	 dirs+=("$item")
-      	 ((item_index++))
-      	 
-      	 [[ $item == "$previous_dir" ]] &&
-      	 ((previous_index=item_index))
+      p) [[ ${marked_files[*]} ]] && {
+	    if [[ ! -w $PWD ]]; then
+	       cmd_line "warn: no write access to dir."
+      	    elif "${file_program[@]}" "${marked_files[@]}" .; then
+	       redraw full
+      	    else
+	       cmd_line "warn: '${file_program[0]}' failed."
+      	    fi
+      	    marked_files=()
+      	    redraw; } ;;
+      V) cmd_line "new text file: "
+	 [[ $cmd_reply ]] && {
+	    reset_terminal
+	    nvim "$cmd_reply"
+	    redraw full; } ;;
+      B) cmd_line "new bash script: "
+	 [[ $cmd_reply ]] && {
+	 [[ ! -f "$cmd_reply" ]] && { 
+	    printf "#!/usr/bin/env bash\n\nmain(){\n<++>\n}\n\nmain \"\$@\"" >\
+	    "$cmd_reply"; chmod a+x "$cmd_reply"; }
+      	 reset_terminal; nvim "$cmd_reply"; redraw full; } ;;
+      F) [[ -f ${list[scroll]} ]] && {
+	    reset_terminal; setup_terminal
+	    chwal -f "${list[scroll]##*/}"; redraw full; } ;;
+      r) cmd_line "rename ${list[scroll]##*/}: "
+	 [[ $cmd_reply ]] &&
+	    if [[ -e $cmd_reply ]]; then
+	       cmd_line "warn: '$cmd_reply' already exists."
+	    elif [[ -w ${list[scroll]} ]]; then
+	       mv "${list[scroll]}" "${PWD}/${cmd_reply}"
+	       redraw full
+	    else
+	       cmd_line "warn: no write access to file."
+	    fi ;;
+      C) cmd_line "\"castnow ${list[scroll]##*/}\" add arguments? [y/n]: " y n
+	 [[ $cmd_reply = y ]] &&
+	    cmd_line "castnow ${list[scroll]##*/} "
+	    cmd_line "\"castnow ${list[scroll]##*/} $cmd_reply\" ready to cast? [y/n]" y n
+	    [[ $cmd_reply != y ]] &&
+	       return
+	    reset_terminal
+	    castnow ${list[scroll]##*/} $cmd_reply
+	    redraw full ;;
+      n) cmd_line "mkdir: " "dirs"
+         [[ $cmd_reply ]] &&
+	    if [[ -e $cmd_reply ]]; then
+	       cmd_line "warn: '$cmd_reply' already exists."
+	    elif [[ -w $PWD ]]; then
+	       mkdir -p "${PWD}/${cmd_reply}"
+	       redraw full
+	    else
+	       cmd_line "warn: no write access to dir."
+	    fi ;;
+      f) cmd_line "mkfile: "
+      [[ $cmd_reply ]] &&
+      if [[ -e $cmd_reply ]]; then
+      cmd_line "warn: '$cmd_reply' already exists."
+      elif [[ -w $PWD ]]; then
+      : > "${PWD}/${cmd_reply}"
+      redraw full
       else
-	 files+=("$item")
-      fi
-   done
-   
-   list=("${dirs[@]}" "${files[@]}")
-   
-   [[ -z ${list[0]} ]] &&
-      list[0]="empty"
-   
-   ((list_total=${#list[@]}-1))
-   
-   cur_list=("${list[@]}")
-}
-
-print_line() {
-   # Format the list item and print it.
-   local file_name="${list[$1]##*/}"
-   local file_ext="${file_name##*.}"
-   local format
-   local suffix
-   
-   # If the dir item doesn't exist, end here.
-   if [[ -z ${list[$1]} ]]; then
-      return
-      
-      # Directory.
-   elif [[ -d ${list[$1]} ]]; then
-      format+="\\e[${di:-1;3${FFF_COL1:-2}}m"
-      suffix+='/'
-      
-      # Block special file.
-   elif [[ -b ${list[$1]} ]]; then
-      format+="\\e[${bd:-40;33;01}m"
-      
-      # Character special file.
-   elif [[ -c ${list[$1]} ]]; then
-      format+="\\e[${cd:-40;33;01}m"
-      
-      # Executable file.
-   elif [[ -x ${list[$1]} ]]; then
-      format+="\\e[${ex:-01;32}m"
-      
-      # Symbolic Link (broken).
-   elif [[ -h ${list[$1]} && ! -e ${list[$1]} ]]; then
-      format+="\\e[${mi:-01;31;7}m"
-      
-      # Symbolic Link.
-   elif [[ -h ${list[$1]} ]]; then
-      format+="\\e[${ln:-01;36}m"
-      
-      # Fifo file.
-   elif [[ -p ${list[$1]} ]]; then
-      format+="\\e[${pi:-40;33}m"
-      
-      # Socket file.
-   elif [[ -S ${list[$1]} ]]; then
-      format+="\\e[${so:-01;35}m"
-      
-   elif [[ $FFF_LS_COLORS == 1 &&
-      $ls_patterns &&
-      $file_name =~ ($ls_patterns)$ ]]; then
-      match="${BASH_REMATCH[0]}"
-      file_ext="ls_${match//[^a-zA-Z0-9=\\;]/_}"
-      format+="\\e[${!file_ext:-${fi:-37}}m"
-
-   elif [[ $FFF_LS_COLORS == 1 &&
-      $file_ext != "$file_name" &&
-      $file_ext =~ ^[a-zA-Z0-9_]*$ ]]; then
-      file_ext="ls_${file_ext}"
-      format+="\\e[${!file_ext:-${fi:-37}}m"
-
-   else
-      format+="\\e[${fi:-37}m"
-   fi
-
-   (($1 == scroll)) &&
-      format+="\\e[1;3${FFF_COL4:-6};7m"
-   
-   [[ ${marked_files[$1]} == "${list[$1]:-null}" ]] && {
-      format+="\\e[3${FFF_COL3:-1}m "
-      suffix+='*'
-   }
-
-   file_name="${file_name//[^[:print:]]/^[}"
-
-   printf '\r%b%s\e[m\r' "$format" "${file_name}${suffix}"
-}
-
-draw_dir() {
-   local scroll_start="$scroll"
-   local scroll_new_pos
-   local scroll_end
-
-   ((find_previous == 1)) && {
-      ((scroll_start=previous_index-1))
-	 ((scroll=scroll_start))
-
-	 find_previous=
-      }
-
-   if ((list_total < max_items || scroll < max_items/2)); then
-      ((scroll_start=0))
-      ((scroll_end=max_items))
-      ((scroll_new_pos=scroll + 1))
-
-   elif ((list_total - scroll < max_items/2)); then
-      ((scroll_start=list_total - max_items + 1))
-      ((scroll_new_pos=max_items - (list_total-scroll)))
-      ((scroll_end=list_total+1))
-
-   else
-      ((scroll_start=scroll-max_items/2))
-      ((scroll_end=scroll_start+max_items))
-      ((scroll_new_pos=max_items/2+1))
-   fi
-
-   for ((i=scroll_start;i<scroll_end;i++)); {
-      # Don't print one too many newlines.
-      ((i > scroll_start)) &&
-	 printf '\n'
-
-      print_line "$i"
-   }
-
-   printf '\e[%sH' "$scroll_new_pos"
-   ((y=scroll_new_pos))
-}
-
-redraw() {
-   [[ $1 == full ]] && { read_dir; scroll=0; }
-   clear_screen; draw_dir; status_line
+      cmd_line "warn: no write access to dir."
+      fi ;;
+      x) clear_screen; stat "${list[scroll]}"; read -rn 1; redraw ;;
+      c) read -rsn 1
+	 case $REPLY in
+	    d) cmd_line "go to dir: " "dirs"
+	    pushd "$PWD" &>/dev/null ||:
+	    [[ $cmd_reply ]] && pushd "${cmd_reply/\~/$HOME}" &>/dev/null && open "$PWD" ;;
+	    c) marked_files=(); redraw full
+	 esac ;;
+      q) : "${FFF_CD_FILE:=${XDG_CACHE_HOME:=${HOME}/.cache}/fff/.fff_d}"
+      printf '%s\n' "$PWD" > "$FFF_CD_FILE"; exit
+   esac
 }
 
 mark() {
-   [[ $PWD != "$mark_dir" ]] &&
-      marked_files=()
+   [[ $PWD != "$mark_dir" ]] && marked_files=()
 
    if [[ ${marked_files[$1]} == "${list[$1]}" ]]; then
       unset 'marked_files[scroll]'
@@ -190,8 +151,7 @@ mark() {
       mark_dir="$PWD"
    fi
 
-   printf '\e[K'
-   print_line "$1"
+   printf '\e[K'; print_line "$1"
 
    case "$2" in
       y) file_program=(cp -R) ;;
@@ -205,43 +165,20 @@ mark() {
 
 trash() {
    cmd_line "trash [${#marked_files[@]}] items? [y/n]: " y n
+   [[ $cmd_reply != y ]] && return; cd "$FFF_TRASH" && "mv" "$@"; cd - &>/dev/null ||:
 
-   [[ $cmd_reply != y ]] &&
-      return
-
-   if [[ $FFF_TRASH_CMD ]]; then
-      "$FFF_TRASH_CMD" "${@:1:$#-1}"
-
-   else
-      cd "$FFF_TRASH" && "mv" "$@"
-
-      cd - &>/dev/null ||:
-   fi
 }
 
 open() {
-   if [[ -d $1/ ]]; then
-      search=
-      search_end_early=
-      previous_dir="$PWD"
-      cd "${1:-/}" ||:
-      redraw full
-
-   elif [[ -f $1 ]]; then
-      mime_type="$(file "-${file_flags:-biL}" "$1")"
-
-      case "$mime_type" in
-	 text/*|*x-empty*|*json*)
-	    reset_terminal
-	    "${EDITOR:-vi}" "$1"
-
-	    setup_terminal
-	    redraw
-	    ;;
-
-	 *) nohup "${FFF_OPENER:-${opener:-xdg-open}}" "$1" &>/dev/null & disown ;;
-      esac
-   fi
+   [[ -d $1/ ]] && {
+      search=""; search_end_early=""; previous_dir="$PWD"
+      cd "${1:-/}" ||:; redraw full; }
+   [[ -f $1 ]] && { mime_type="$(file "-${file_flags:-biL}" "$1")"
+   case "$mime_type" in
+      text/*|*x-empty*|*json*)
+      reset_terminal; "${EDITOR:-vi}" "$1"; setup_terminal; redraw ;;
+      *) nohup "${FFF_OPENER:-${opener:-xdg-open}}" "$1" &>/dev/null & disown ;;
+   esac; }
 }
 
 cmd_line() {
@@ -302,222 +239,117 @@ cmd_line() {
    printf '\e[2K\e[?6h\e[?25l\e8'
 }
 
-short() {
-   previous_dir="$PWD"
-   case "${1: -1}" in
-      /) open "/" ;;
-      a) open "$HOME/.apps" ;;
-      h) open "$HOME/Hentet" ;;
-      b) open "$HOME/.bin" ;;
-      S) open "$HOME/.Scripts" ;;
-      p) open "$HOME/Projekter" ;;
-      d) open "$HOME/.dotfiles" ;;
-      D) open "$HOME/Dokumenter" ;;
-      c) open "$HOME/.config" ;;
-      l) open "$HOME/.local" ;;
-      w) open "$HOME/Billeder/wallpapers" ;;
-      t) open "$HOME/.cache/fff/trash" ;;
-      y) open "$HOME/Movies/youtube" ;;
+status_line() {
+   local mark_ui="[${#marked_files[@]}] selected (${file_program[*]}) [p] ->"
 
-      g) ((scroll != 0)) && ((scroll=0)) ;;
-   esac
-   redraw
+   PWD_escaped="${PWD//[^[:print:]]/^[}"
+
+   printf '\e7\e[?6l\e[%sH\e[30;4%sm%*s\r%s %s%s\e[m\n\e[K\e[?6h\e8' \
+      "$((LINES-1))" "${FFF_COL2:-1}" "$COLUMNS" "" "($((scroll+1))/$((list_total+1)))" \
+      "${marked_files[*]:+${mark_ui}}" "${PWD_escaped:-/}"
 }
 
-key() {
-   case "$1" in
-      l|"") open "${list[scroll]}" ;;
-
-      h) 
-	 ((search == 1 && search_end_early != 1)) && open "$PWD"
-	 [[ $PWD && $PWD != / ]] && { 
-	    find_previous=1; open "${PWD%/*}"
-	 }
-      ;;
-
-      j) ((scroll < list_total)) && {
-	    ((scroll++)); ((y < max_items )) && ((y++))
-	    print_line "$((scroll-1))"
-	    printf '\n'
-	    print_line "$scroll"
-	    status_line
-	 }
-      ;;
-
-      k)
-	 ((scroll > 0)) && {
-	    ((scroll--))
-	    print_line "$((scroll+1))"
-	    ((y < 2)) && printf '\e[1L' || printf '\e[A' || ((y--))
-	    print_line "$scroll"
-	    status_line
-	 }
-      ;;
-
-      g) read -rsn 1; short "$REPLY" ;;
-      G) ((scroll != list_total)) && ((scroll=list_total)) && redraw ;;
-      O) xdg-open "${list[scroll]}" 2>/dev/null & disown ;;
-
-      R) [[ -x "${list[scroll]}" ]] && {
-	    reset_terminal
-      	    "${list[scroll]}"
-      	    read &>/dev/null
-      	    redraw full
-      	 }
-      ;;
-
-      .) shopt_flags=(u s)
-	 shopt -"${shopt_flags[((a=a>0?0:++a))]}" dotglob
-      	 redraw full
-      ;;
-
-      /) 
-	    cmd_line "/" "search"
-	    if [[ -z ${list[*]} || -z $cmd_reply ]]; then
-	       list=("${cur_list[@]}")
-      	       ((list_total=${#list[@]}-1))
-      	       redraw
-      	       search=
-      	    else
-	       search=1
-      	    fi
-      ;;
-
-      S) reset_terminal; cd "$PWD" && "$SHELL"
-	 setup_terminal; redraw 
-      ;;
-
-      y|m|d|v) mark "$scroll" "$1" ;;
-
-      p) 
-	 [[ ${marked_files[*]} ]] && {
-	    if [[ ! -w $PWD ]]; then
-	       cmd_line "warn: no write access to dir."
-      	    elif "${file_program[@]}" "${marked_files[@]}" .; then
-	       redraw full
-      	    else
-	       cmd_line "warn: '${file_program[0]}' failed."
-      	    fi
-      	    marked_files=()
-      	    redraw
-	 }
-      ;;
-
-      V) 
-	 cmd_line "new text file: "
-	 [[ $cmd_reply ]] && {
-	    reset_terminal
-	    nvim "$cmd_reply"
-	    redraw full
-	 }
-      ;;
-
-      B)
-	 cmd_line "new bash script: "
-	 [[ $cmd_reply ]] && {
-	 [[ ! -f "$cmd_reply" ]] && { 
-	    printf "#!/usr/bin/env bash\n\nmain(){\n<++>\n}\n\nmain \"\$@\"" >\
-	    "$cmd_reply" 
-      	    chmod a+x "$cmd_reply"
-      	 }
-      	 reset_terminal
-      	 nvim "$cmd_reply"
-      	 redraw full
-      }
-      ;;
-
-      F)
-	 [[ -f ${list[scroll]} ]] && {
-	    reset_terminal
-	    setup_terminal
-	    chwal -f "${list[scroll]##*/}"
-	    redraw full
-	 }
-      ;;
-
-      r) cmd_line "rename ${list[scroll]##*/}: "
-	 [[ $cmd_reply ]] &&
-	    if [[ -e $cmd_reply ]]; then
-	       cmd_line "warn: '$cmd_reply' already exists."
-	    elif [[ -w ${list[scroll]} ]]; then
-	       mv "${list[scroll]}" "${PWD}/${cmd_reply}"
-	       redraw full
-	    else
-	       cmd_line "warn: no write access to file."
-	    fi
-      ;;
-      C) cmd_line "\"castnow ${list[scroll]##*/}\" add arguments? [y/n]: " y n
-	 [[ $cmd_reply = y ]] &&
-	    cmd_line "castnow ${list[scroll]##*/} "
-	    cmd_line "\"castnow ${list[scroll]##*/} $cmd_reply\" ready to cast? [y/n]" y n
-	    [[ $cmd_reply != y ]] &&
-	       return
-	    reset_terminal
-	    castnow ${list[scroll]##*/} $cmd_reply
-	    redraw full
-      ;;
-
-      n) cmd_line "mkdir: " "dirs"
-         [[ $cmd_reply ]] &&
-	    if [[ -e $cmd_reply ]]; then
-	       cmd_line "warn: '$cmd_reply' already exists."
-	    elif [[ -w $PWD ]]; then
-	       mkdir -p "${PWD}/${cmd_reply}"
-	       redraw full
-	    else
-	       cmd_line "warn: no write access to dir."
-	    fi
-      ;;
-      f) cmd_line "mkfile: "
-      [[ $cmd_reply ]] &&
-      if [[ -e $cmd_reply ]]; then
-      cmd_line "warn: '$cmd_reply' already exists."
-      elif [[ -w $PWD ]]; then
-      : > "${PWD}/${cmd_reply}"
-      redraw full
+read_dir() {
+   local dirs=(); local files=(); local item_index
+   
+   # If '$PWD' is '/', unset it to avoid '//'.
+   [[ $PWD == / ]] && PWD=
+   
+   for item in "$PWD"/*; do
+      if [[ -d $item ]]; then
+	 dirs+=("$item")
+      	 ((item_index++))
+      	 
+      	 [[ $item == "$previous_dir" ]] &&
+      	 ((previous_index=item_index))
       else
-      cmd_line "warn: no write access to dir."
-      fi ;;
-      x) clear_screen; stat "${list[scroll]}"; read -rn 1; redraw ;;
-      c) read -rsn 1
-	 case $REPLY in
-	    d) cmd_line "go to dir: " "dirs"
-	    pushd "$PWD" &>/dev/null ||:
-	    [[ $cmd_reply ]] && pushd "${cmd_reply/\~/$HOME}" &>/dev/null && open "$PWD"
-	    ;;
-	    c) marked_files=(); redraw full
-	 esac
-      ;;
-      	# Go to '$HOME'.
-      "${FFF_KEY_GO_HOME:=~}")
-      open ~
-      ;;
-      # Go to trash.
-      "${FFF_KEY_GO_TRASH:=t}")
-      open "$FFF_TRASH"
-      ;;
-      # Go to previous dir.
-      "${FFF_KEY_PREVIOUS:=-}")
-      open "$previous_dir"
-      ;;
-      # Directory favourites.
-      [1-9])
-      favourite="FFF_FAV${1}"
-      favourite="${!favourite}"
-      
-      [[ $favourite ]] &&
-      open "$favourite"
-      ;;
-      # Quit and store current directory in a file for CD on exit.
-      # Don't allow user to redefine 'q' so a bad keybinding doesn't
-      # remove the option to quit.
-      q)
-      : "${FFF_CD_FILE:=${XDG_CACHE_HOME:=${HOME}/.cache}/fff/.fff_d}"
-      printf '%s\n' "$PWD" > "$FFF_CD_FILE"
-      exit
-      ;;
-   esac
+	 files+=("$item")
+      fi
+   done
+   
+   list=("${dirs[@]}" "${files[@]}")
+   
+   [[ -z ${list[0]} ]] && list[0]="empty"
+   
+   ((list_total=${#list[@]}-1))
+   
+   cur_list=("${list[@]}")
 }
+
+print_line() {
+   local file_name="${list[$1]##*/}"
+   local file_ext="${file_name##*.}"
+   local format; local suffix
+   
+   format+="\\e[${fi:-37}m"
+   [[ -z ${list[$1]} ]] && return
+   [[ -d ${list[$1]} ]] && {
+      format+="\\e[${di:-1;3${FFF_COL1:-2}}m"
+      suffix+='/'; }
+   [[ -b ${list[$1]} ]] && format+="\\e[${bd:-40;33;01}m"
+   [[ -c ${list[$1]} ]] && format+="\\e[${cd:-40;33;01}m"
+   [[ -x ${list[$1]} ]] && format+="\\e[${ex:-01;32}m"
+   [[ -h ${list[$1]} && ! -e ${list[$1]} ]] && format+="\\e[${mi:-01;31;7}m"
+   [[ -h ${list[$1]} ]] && format+="\\e[${ln:-01;36}m"
+   [[ -p ${list[$1]} ]] && format+="\\e[${pi:-40;33}m"
+   [[ -S ${list[$1]} ]] && format+="\\e[${so:-01;35}m"
+
+   (($1 == scroll)) && format+="\\e[1;3${FFF_COL4:-6};7m"
+   
+   [[ ${marked_files[$1]} == "${list[$1]:-null}" ]] && {
+      format+="\\e[3${FFF_COL3:-1}m "
+      suffix+='*'; }
+
+   file_name="${file_name//[^[:print:]]/^[}"
+
+   printf '\r%b%s\e[m\r' "$format" "${file_name}${suffix}"
+}
+
+draw_dir() {
+   local scroll_start="$scroll"; local scroll_new_pos; local scroll_end
+
+   ((find_previous == 1)) && {
+      ((scroll_start=previous_index-1))
+      ((scroll=scroll_start))
+      find_previous=
+   }
+
+   if ((list_total < max_items || scroll < max_items/2)); then
+      ((scroll_start=0))
+      ((scroll_end=max_items))
+      ((scroll_new_pos=scroll + 1))
+
+   elif ((list_total - scroll < max_items/2)); then
+      ((scroll_start=list_total - max_items + 1))
+      ((scroll_new_pos=max_items - (list_total-scroll)))
+      ((scroll_end=list_total+1))
+
+   else
+      ((scroll_start=scroll-max_items/2))
+      ((scroll_end=scroll_start+max_items))
+      ((scroll_new_pos=max_items/2+1))
+   fi
+
+   for ((i=scroll_start;i<scroll_end;i++)); {
+      ((i > scroll_start)) && printf '\n'
+      print_line "$i"; }
+
+   printf '\e[%sH' "$scroll_new_pos"
+   ((y=scroll_new_pos))
+}
+
+redraw() {
+   [[ $1 == full ]] && { read_dir; scroll=0; }
+   clear_screen; draw_dir; status_line
+}
+
+clear_screen() { printf '\e[%sH\e[9999C\e[1J%b\e[1;%sr' "$((LINES-2))" "${TMUX:+\e[2J}" "$max_items"; }
+
+setup_terminal() { printf '\e[?1049h\e[?6h\e[?7l\e[?25l\e[2J\e[1;%sr' "$max_items"; }
+
+get_term_size() { read -r LINES COLUMNS < <(stty size); ((max_items=LINES-3)); }
+
+reset_terminal() { printf '\e[?6l\e[?7h\e[?25h\e[2J\e[;r'; }
 
 main() {
    pushd "$1" &>/dev/null ||:
